//
// Quality Trimming & Filtering, Adaptor Trimming, and QC Check
//
include { FASTP                 } from '../../../modules/local/preprocess/fastp/main'
include { PARSE_FASTP_REPORTS   } from '../../../modules/local/preprocess/parse_fastp/main'
include { COMBINE_FASTP_REPORTS } from '../../../modules/local/preprocess/combine_reports/main'
include { FASTP_QC_CHECK        } from '../../../modules/local/preprocess/fastp_qc/main'

workflow PREPROCESSING {
    take:
    reads          // channel: [ meta, [ reads ] ]
    prefix         // val(prefix)

    main:

    ch_versions = Channel.empty()

    //
    // Quality trimming & filtering and adaptor trimming with fastp
    //
    ch_fastq = Channel.empty()
    FASTP (
        reads
    )
    ch_fastq = FASTP.out.fastq_4_processing_files
    ch_versions = ch_versions.mix(FASTP.out.versions)

    //
    // Parse JSON report generated by fastp & report relevant FASTQ quality metrics 
    //
    ch_fastp_report = Channel.empty()
    PARSE_FASTP_REPORTS (
        FASTP.out.json_path
    )
    ch_fastp_report = PARSE_FASTP_REPORTS.out.tsv_path
    ch_versions = ch_versions.mix(PARSE_FASTP_REPORTS.out.versions)

    //
    // Combine reports for all samples into one report
    //
    COMBINE_FASTP_REPORTS (
        ch_fastp_report.collect(),
        prefix
    )
    ch_versions = ch_versions.mix(COMBINE_FASTP_REPORTS.out.versions)

    //
    // Perform QC check and create reports containing the passed & failed samples
    //
    FASTP_QC_CHECK (
        COMBINE_FASTP_REPORTS.out.fastp_report,
        prefix
    )
    ch_versions = ch_versions.mix(FASTP_QC_CHECK.out.versions)

    ch_qc = Channel.empty()
    ch_qc = FASTP_QC_CHECK.out
            .passed
            .splitCsv ( header:true, sep:'\t' )
            .map { row -> "${row.isolate}" }
            
    ch_fastq2 = ch_fastq
            .map { 
                meta, fastqs ->
                    [ meta.id, fastqs ]
            }
    ch_qc2 = ch_qc
            .map {
                meta ->
                    [ meta, 'placeholder' ]
            }

    ch_passed = Channel.empty()

    ch_passed = ch_qc2.join(ch_fastq2)
                        .map {
                            meta, placeholder, fastqs ->
                            [ [ id:meta ], fastqs ]
                        }

    emit:

    fastp_report        = COMBINE_FASTP_REPORTS.out.fastp_report        // channel:  fastp_report 
    fastp_json          = FASTP.out.json_path                           // channel:  [ meta, [ json_path ] ]

    passed              = FASTP_QC_CHECK.out.passed                     // channel: path(passed)
    failed              = FASTP_QC_CHECK.out.failed                     // channel: path(failed)

    trimmed_fastq_paths = ch_passed                                     // channel: [ meta, [ trimmed_fastq_paths ] ]

    versions            = ch_versions                                   // channel: [ versions.yml ]

}